language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"

install:
  - "pip install -r requirements_dev.txt"
  - "pip install coveralls"

env:
  - PYTHONPATH=`pwd`

script:
  - py.test

after_script:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: always
