language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install -r requirements_dev.txt"
  - "pip install coveralls"

script:
  # - "python setup.py install"
  - "py.test"

after_script:
  - "coveralls"

notifications:
  email:
    on_success: change
    on_failure: always
